ex.analyze_streaks = true
RISK_FACTOR = 1
RISK_MULTIPLIER = 0
RISK_BASE = 1
BET_PERCENT_FROM_BK = 100
minProfit = -400000
maxProfit = 800000
simulation = false
simulation_balance = 100000
ex.increase_basebet_after_streak = -1
ex.increase_basebet_on_wins = 100
ex.increase_basebet_times = 100
game_array.push(new Strategy(10, 300, 15, 7, 1.2, true));game_array[ 0 ].target = 10
game_array[ 0 ].basebet = 300
game_array[ 0 ].basebet_default = 300
game_array[ 0 ].bet = 300
game_array[ 0 ].MAX_BET_TURNS = 15
game_array[ 0 ].STW = 7
game_array[ 0 ].multiplier = 1.2
game_array[ 0 ].enabled = true
game_array[ 0 ].Settings.bet.multiplier = 1.2
game_array[ 0 ].Settings.bet.base = 300
game_array[ 0 ].Settings.bet.mode = "mul"
game_array[ 0 ].Settings.bet.minimal = 100
game_array[ 0 ].Settings.bet.maximal = 213472500000
game_array[ 0 ].Settings.bet.return_at.RETURN_BASE = true
game_array[ 0 ].Settings.bet.return_at.on_win = true
game_array[ 0 ].Settings.bet.return_at.on_lose = false
game_array[ 0 ].Settings.target.multiplier = 1
game_array[ 0 ].Settings.target.base = 10
game_array[ 0 ].Settings.target.mode = "mul"
game_array[ 0 ].Settings.target.minimal = 1.01
game_array[ 0 ].Settings.target.maximal = 10000
game_array[ 0 ].Settings.target.return_at.return = false
game_array[ 0 ].Settings.target.return_at.on_win = true
game_array[ 0 ].Settings.target.return_at.on_lose = false
